name: SwaggerHub Integration
on: workflow_dispatch
jobs:
  Hello:
   runs-on: ubuntu-latest
   steps:
      - name: Update swagerHub
        run: |
         sh ./.github/workflows/apicall.sh
        shell: bash
